import { Body, Controller, Get, Param, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { PlatformRole, Prisma } from '@prisma/client';
import { CurrentContext } from '../common/decorators/current-context.decorator'; import { Roles } from '../common/decorators/roles.decorator'; import { JwtAuthGuard } from '../common/guards/jwt-auth.guard'; import { RolesGuard } from '../common/guards/roles.guard'; import { RequestContext } from '../common/types/request-context'; import { PrismaService } from '../prisma/prisma.service'; import { CreateExpenseDto,UpdateExpenseDto } from './expenses.dto';
@Controller('expenses') @UseGuards(JwtAuthGuard,RolesGuard)
export class ExpensesController{constructor(private prisma:PrismaService){}
 @Get() @Roles(PlatformRole.COMMUNITY_ADMIN,PlatformRole.TREASURER,PlatformRole.SUPER_ADMIN) async list(@CurrentContext() c:RequestContext,@Query('eventId') eventId?:string){return{success:true,data:await this.prisma.expense.findMany({where:{tenantId:c.tenantId,communityId:c.communityId,...(eventId?{eventId}: {})},include:{category:true,event:true},orderBy:{expenseDate:'desc'}})}}
 @Post() @Roles(PlatformRole.COMMUNITY_ADMIN,PlatformRole.TREASURER,PlatformRole.SUPER_ADMIN) async create(@CurrentContext() c:RequestContext,@Body() d:CreateExpenseDto){await this.prisma.event.findFirstOrThrow({where:{id:d.eventId,tenantId:c.tenantId,communityId:c.communityId}});return{success:true,data:await this.prisma.expense.create({data:{tenantId:c.tenantId,communityId:c.communityId,eventId:d.eventId,categoryId:d.categoryId,description:d.description,vendorName:d.vendorName,amount:new Prisma.Decimal(d.amount),expenseDate:new Date(d.expenseDate),receiptUrl:d.receiptUrl}})}}
 @Patch(':id') @Roles(PlatformRole.COMMUNITY_ADMIN,PlatformRole.TREASURER,PlatformRole.SUPER_ADMIN) async update(@CurrentContext() c:RequestContext,@Param('id') id:string,@Body() d:UpdateExpenseDto){const row=await this.prisma.expense.findFirstOrThrow({where:{id,tenantId:c.tenantId,communityId:c.communityId}});return{success:true,data:await this.prisma.expense.update({where:{id:row.id},data:{...d,amount:d.amount!==undefined?new Prisma.Decimal(d.amount):undefined,expenseDate:d.expenseDate?new Date(d.expenseDate):undefined}})}}
}
