import { BadRequestException, Body, Controller, Get, Param, Patch, Post, UseGuards } from '@nestjs/common';
import { PlatformRole } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { CurrentContext } from '../common/decorators/current-context.decorator'; import { Roles } from '../common/decorators/roles.decorator'; import { JwtAuthGuard } from '../common/guards/jwt-auth.guard'; import { RolesGuard } from '../common/guards/roles.guard'; import { RequestContext } from '../common/types/request-context'; import { BulkUpdateSessionDto, CreateSessionDto, GenerateSessionsDto, UpdateSessionDto } from './sessions.dto';
@Controller('events/:eventId/sessions') @UseGuards(JwtAuthGuard,RolesGuard)
export class SessionsController { constructor(private prisma:PrismaService){}
  private validateTimes(startTime?:string,endTime?:string){if(startTime&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(startTime))throw new BadRequestException('Start time must use HH:MM');if(endTime&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(endTime))throw new BadRequestException('End time must use HH:MM');if(startTime&&endTime&&startTime>=endTime)throw new BadRequestException('End time must be after start time');}
  @Get() async list(@CurrentContext() c:RequestContext,@Param('eventId') eventId:string){const e=await this.prisma.event.findFirstOrThrow({where:{id:eventId,tenantId:c.tenantId,communityId:c.communityId}});return{success:true,data:await this.prisma.eventSession.findMany({where:{eventId:e.id},include:{_count:{select:{bookings:{where:{status:'CONFIRMED'}},waitlist:{where:{cancelledAt:null,promotedAt:null}}}}},orderBy:{sessionDate:'asc'}})}}
  @Post('generate') @Roles(PlatformRole.COMMUNITY_ADMIN,PlatformRole.EVENT_ADMIN,PlatformRole.SUPER_ADMIN)
  async generate(@CurrentContext() c:RequestContext,@Param('eventId') eventId:string,@Body() d:GenerateSessionsDto){const e=await this.prisma.event.findFirstOrThrow({where:{id:eventId,tenantId:c.tenantId,communityId:c.communityId}});const rows=[];for(let day=new Date(e.startDate);day<=e.endDate;day=new Date(day.getTime()+86400000)){rows.push({tenantId:c.tenantId,communityId:c.communityId,eventId:e.id,name:d.name??'Daily Pooja',sessionType:d.sessionType??'DAILY',sessionDate:new Date(day),startTime:d.startTime??'08:00',endTime:d.endTime??'10:00',capacity:d.capacity,allowWaitlist:d.allowWaitlist??true});}await this.prisma.eventSession.createMany({data:rows,skipDuplicates:true});return{success:true,data:await this.prisma.eventSession.findMany({where:{eventId:e.id},orderBy:{sessionDate:'asc'}})};}
  @Post() @Roles(PlatformRole.COMMUNITY_ADMIN,PlatformRole.EVENT_ADMIN,PlatformRole.SUPER_ADMIN)
  async create(@CurrentContext() c:RequestContext,@Param('eventId') eventId:string,@Body() d:CreateSessionDto){const e=await this.prisma.event.findFirstOrThrow({where:{id:eventId,tenantId:c.tenantId,communityId:c.communityId}});this.validateTimes(d.startTime,d.endTime);const date=new Date(d.sessionDate);if(date<new Date(e.startDate)||date>new Date(e.endDate))throw new BadRequestException('Special pooja date must be within the event dates');return{success:true,data:await this.prisma.eventSession.create({data:{tenantId:c.tenantId,communityId:c.communityId,eventId:e.id,name:d.name.trim(),sessionType:d.sessionType??'SPECIAL',sessionDate:date,startTime:d.startTime,endTime:d.endTime,capacity:d.capacity,allowWaitlist:d.allowWaitlist??true}})};}
  @Patch('bulk') @Roles(PlatformRole.COMMUNITY_ADMIN,PlatformRole.EVENT_ADMIN,PlatformRole.SUPER_ADMIN)
  async bulkUpdate(@CurrentContext() c:RequestContext,@Param('eventId') eventId:string,@Body() d:BulkUpdateSessionDto){const sessions=await this.prisma.eventSession.findMany({where:{eventId,tenantId:c.tenantId,communityId:c.communityId,sessionType:'DAILY'},include:{_count:{select:{bookings:{where:{status:'CONFIRMED'}}}}}});this.validateTimes(d.startTime,d.endTime);if(d.capacity&&sessions.some(s=>d.capacity!<s._count.bookings))throw new BadRequestException('Capacity cannot be below an existing confirmed booking count');const {name,startTime,endTime,capacity,allowWaitlist}=d;await this.prisma.eventSession.updateMany({where:{eventId,tenantId:c.tenantId,communityId:c.communityId,sessionType:'DAILY'},data:{...(name!==undefined?{name}:{}),...(startTime!==undefined?{startTime}:{}),...(endTime!==undefined?{endTime}:{}),...(capacity!==undefined?{capacity}:{}),...(allowWaitlist!==undefined?{allowWaitlist}:{})}});return{success:true,data:await this.prisma.eventSession.findMany({where:{eventId},orderBy:{sessionDate:'asc'}})};}
  @Patch(':id') @Roles(PlatformRole.COMMUNITY_ADMIN,PlatformRole.EVENT_ADMIN,PlatformRole.SUPER_ADMIN)
  async update(@CurrentContext() c:RequestContext,@Param('eventId') eventId:string,@Param('id') id:string,@Body() d:UpdateSessionDto){const session=await this.prisma.eventSession.findFirstOrThrow({where:{id,eventId,tenantId:c.tenantId,communityId:c.communityId}});this.validateTimes(d.startTime,d.endTime);if(d.capacity){const confirmed=await this.prisma.eventBooking.count({where:{sessionId:id,status:'CONFIRMED'}});if(d.capacity<confirmed)throw new BadRequestException(`Capacity cannot be below ${confirmed} confirmed bookings`);}return{success:true,data:await this.prisma.eventSession.update({where:{id:session.id},data:d})};}
}
