import { Controller, Get, UseGuards } from '@nestjs/common'; import { PlatformRole, Prisma } from '@prisma/client'; import { PrismaService } from '../prisma/prisma.service'; import { CurrentContext } from '../common/decorators/current-context.decorator'; import { Roles } from '../common/decorators/roles.decorator'; import { JwtAuthGuard } from '../common/guards/jwt-auth.guard'; import { RolesGuard } from '../common/guards/roles.guard'; import { RequestContext } from '../common/types/request-context';
@Controller() @UseGuards(JwtAuthGuard,RolesGuard)
export class DashboardController{constructor(private prisma:PrismaService){}
 @Get('me/dashboard') async me(@CurrentContext() c:RequestContext){const events=await this.prisma.event.findMany({where:{tenantId:c.tenantId,communityId:c.communityId,status:{in:['PUBLISHED','ACTIVE']}},orderBy:{startDate:'asc'},take:10});const anns=await this.prisma.announcement.findMany({where:{tenantId:c.tenantId,communityId:c.communityId,publishedAt:{not:null}},orderBy:{publishedAt:'desc'},take:5});const membership=c.unitId?await this.prisma.unitMembership.findFirst({where:{unitId:c.unitId,userId:c.userId},include:{unit:{include:{building:true}}}}):null;return{success:true,data:{unit:membership?{id:membership.unitId,displayName:`${membership.unit.building.code}-${membership.unit.unitNumber}`}:null,events,announcements:anns}}}
 @Get('admin/dashboard') @Roles(PlatformRole.COMMUNITY_ADMIN,PlatformRole.TREASURER,PlatformRole.EVENT_ADMIN,PlatformRole.SUPER_ADMIN)
 async admin(@CurrentContext() c:RequestContext){const [units,residents,events,pending,verified,expenses]=await Promise.all([this.prisma.unit.count({where:{tenantId:c.tenantId,communityId:c.communityId,isActive:true}}),this.prisma.user.count({where:{tenantId:c.tenantId,roles:{some:{communityId:c.communityId,role:'RESIDENT'}}}}),this.prisma.event.count({where:{tenantId:c.tenantId,communityId:c.communityId}}),this.prisma.payment.count({where:{tenantId:c.tenantId,communityId:c.communityId,status:'MANUAL_PENDING'}}),this.prisma.payment.aggregate({where:{tenantId:c.tenantId,communityId:c.communityId,status:'VERIFIED'},_sum:{amount:true}}),this.prisma.expense.aggregate({where:{tenantId:c.tenantId,communityId:c.communityId},_sum:{amount:true}})]);return{success:true,data:{units,residents,events,pendingPayments:pending,verifiedAmount:verified._sum.amount??new Prisma.Decimal(0),expenseAmount:expenses._sum.amount??new Prisma.Decimal(0)}}}
 @Get('reports/contributions') @Roles(PlatformRole.COMMUNITY_ADMIN,PlatformRole.TREASURER,PlatformRole.SUPER_ADMIN)
 async contributions(@CurrentContext() c:RequestContext){const rows=await this.prisma.contribution.findMany({where:{tenantId:c.tenantId,communityId:c.communityId},include:{unit:{include:{building:true,memberships:{where:{endsAt:null},include:{user:true}}}},campaign:{include:{event:true}}},orderBy:{createdAt:'desc'}});const expected=rows.reduce((s,r)=>s+Number(r.expectedAmount),0),paid=rows.reduce((s,r)=>s+Number(r.paidAmount),0);return{success:true,data:{summary:{rows:rows.length,expectedAmount:expected,paidAmount:paid,pendingAmount:Math.max(0,expected-paid)},rows:rows.map(r=>({id:r.id,event:r.campaign.event.name,unit:`${r.unit.building.code}-${r.unit.unitNumber}`,resident:r.unit.memberships[0]?.user.firstName??'',expectedAmount:Number(r.expectedAmount),paidAmount:Number(r.paidAmount),status:r.status}))}}}
}
