import { Navigate, Route, Routes } from 'react-router-dom';
import { useAuth } from './auth/AuthContext';
import LoginPage from './pages/LoginPageSimple'; import RegisterPage from './pages/RegisterPage'; import ForgotPasswordPage from './pages/ForgotPasswordPage'; import ResetPasswordPage from './pages/ResetPasswordPage';
import ResidentLayout from './layouts/ResidentLayout'; import AdminLayout from './layouts/AdminLayout';
import ResidentDashboardPage from './pages/ResidentDashboardPage'; import ResidentEventPage from './pages/ResidentEventPage'; import AdminDashboardPage from './pages/AdminDashboardPage'; import ResidentsPage from './pages/ResidentsPage'; import BuildingsUnitsPage from './pages/BuildingsUnitsPage'; import EventsPage from './pages/EventsPage'; import EventManagePage from './pages/EventManagePage'; import EventAttendeesPage from './pages/EventAttendeesPage'; import EventAttendeesIndexPage from './pages/EventAttendeesIndexPage'; import PaymentsPage from './pages/PaymentsPage'; import ReportsPage from './pages/ReportsPage'; import MastersPage from './pages/MastersPage'; import ExpensesPage from './pages/ExpensesPageEnhanced'; import AnnouncementsPage from './pages/AnnouncementsPage'; import ChangePasswordPage from './pages/ChangePasswordPage';
function Protected({ admin=false, children }: { admin?: boolean; children: any }) { const { user, isAdmin } = useAuth(); if (!user) return <Navigate to="/login" replace />; if (user.mustChangePassword) return <Navigate to="/change-password" replace />; if (admin && !isAdmin) return <Navigate to="/app/dashboard" replace />; return children; }
export default function App() { const { user, isAdmin } = useAuth(); return <Routes>
  <Route path="/login" element={user ? <Navigate to={user.mustChangePassword ? '/change-password' : isAdmin ? '/admin/dashboard' : '/app/dashboard'} replace /> : <LoginPage />} />
  <Route path="/register" element={<RegisterPage />} /><Route path="/forgot-password" element={<ForgotPasswordPage />} /><Route path="/reset-password" element={<ResetPasswordPage />} />
  <Route path="/change-password" element={!user ? <Navigate to="/login" replace /> : <ChangePasswordPage />} />
  <Route path="/app" element={<Protected><ResidentLayout /></Protected>}><Route path="dashboard" element={<ResidentDashboardPage />} /><Route path="events/:id" element={<ResidentEventPage />} /></Route>
  <Route path="/admin" element={<Protected admin><AdminLayout /></Protected>}><Route path="dashboard" element={<AdminDashboardPage />} /><Route path="residents" element={<ResidentsPage />} /><Route path="buildings" element={<BuildingsUnitsPage />} /><Route path="events" element={<EventsPage />} /><Route path="event-attendees" element={<EventAttendeesIndexPage />} /><Route path="events/:id" element={<EventManagePage />} /><Route path="events/:id/attendees" element={<EventAttendeesPage />} /><Route path="payments" element={<PaymentsPage />} /><Route path="expenses" element={<ExpensesPage />} /><Route path="announcements" element={<AnnouncementsPage />} /><Route path="reports" element={<ReportsPage />} /><Route path="masters" element={<MastersPage />} /></Route>
  <Route path="*" element={<Navigate to={user ? isAdmin ? '/admin/dashboard' : '/app/dashboard' : '/login'} replace />} />
</Routes>; }
